name: Dash-Cognito-Auth

on:
  push:
    branches: ["*"]
  # pull_request:
  #   branches: [master]

  # Trigger on release, this will cause the upload to Pypi
  release:
    types:
      - created

jobs:
  cross_platform_tests:
    runs-on: ${{ matrix.os }}
    environment: end-2-end-tests
    env:
      COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
      COGNITO_EMAIL: ${{ secrets.COGNITO_EMAIL }}
      COGNITO_OAUTH_CLIENT_ID: ${{ secrets.COGNITO_OAUTH_CLIENT_ID }}
      COGNITO_OAUTH_CLIENT_SECRET: ${{ secrets.COGNITO_OAUTH_CLIENT_SECRET }}
      COGNITO_PASSWORD: ${{ secrets.COGNITO_PASSWORD }}
      COGNITO_REGION: ${{ secrets.COGNITO_REGION }}
      COGNITO_USER_NAME: ${{ secrets.COGNITO_USER_NAME }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        pythonVersion: ["3.10"] # , "3.11", "3.12"

      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonVersion }}

      - name: Install dev dependencies
        run: pip install -e ".[dev]"

      - name: Run Tests
        run: python setup.py test
